[package]
name = "clipsaver"
version = "0.1.0"
authors = ["Terry Lewis <terry@ploverproductions.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
urlencoding = "1.0.0"
structopt = "0.3"